name: Deploy Node Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t harshkandera/biddrive:latest .

      - name: Publish Image to Docker Hub
        run: docker push harshkandera/biddrive:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
     - name: Fix Docker socket permissions
        run: sudo chmod 666 /var/run/docker.sock
        
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull image from Docker Hub
        run: docker pull harshkandera/biddrive:latest

      - name: Delete old container
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name nodejs-app-container -e MONOGODB_URL='${{ secrets.MONOGODB_URL }}' -e JWT_SECRET='${{ secrets.JWT_SECRET }}' -e CLOUD_NAME='${{ secrets.CLOUD_NAME }}' -e API_KEY='${{ secrets.API_KEY }}' -e API_SECRET='${{ secrets.API_SECRET }}' -e MAIL_HOST='${{ secrets.MAIL_HOST }}' -e MAIL_PASS='${{ secrets.MAIL_PASS }}' -e MAIL_USER='${{ secrets.MAIL_USER }}' -e NODE_ENV='production' -e PORT='${{ secrets.PORT }}' harshkandera/biddrive:latest
